openapi: 3.0.1
info:
  contact:
    email: contact@snippets.local
  description: Test description
  license:
    name: BSD License
  termsOfService: https://www.google.com/policies/terms/
  title: Snippets API
  version: v1
servers:
- url: http://localhost:8000/api
security:
- Basic: []
paths:
  /branch/:
    get:
      operationId: branch_list
      parameters:
      - in: query
        name: with_uuid
        schema:
          type: string
      - in: query
        name: with_code
        schema:
          type: string
      - in: query
        name: with_name
        schema:
          type: string
      - in: query
        name: with_effectiveDate
        schema:
          type: string
      - in: query
        name: with_expirationDate
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Branch'
                type: array
          description: ""
      tags:
      - branch
      x-accepts: application/json
    post:
      operationId: branch_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ""
      tags:
      - branch
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
  /branch/{itemIdentifier}/:
    delete:
      operationId: branch_delete
      parameters:
      - description: A unique value identifying this branch.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "204":
          content: {}
          description: ""
      tags:
      - branch
      x-accepts: application/json
    get:
      operationId: branch_read
      parameters:
      - description: A unique value identifying this branch.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ""
      tags:
      - branch
      x-accepts: application/json
    patch:
      operationId: branch_partial_update
      parameters:
      - description: A unique value identifying this branch.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ""
      tags:
      - branch
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
    put:
      operationId: branch_update
      parameters:
      - description: A unique value identifying this branch.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ""
      tags:
      - branch
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
  /dealer/:
    get:
      operationId: dealer_list
      parameters:
      - in: query
        name: with_uuid
        schema:
          type: string
      - in: query
        name: with_code
        schema:
          type: string
      - in: query
        name: with_name
        schema:
          type: string
      - in: query
        name: with_effectiveDate
        schema:
          type: string
      - in: query
        name: with_expirationDate
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Dealer'
                type: array
          description: ""
      tags:
      - dealer
      x-accepts: application/json
    post:
      operationId: dealer_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dealer'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
          description: ""
      tags:
      - dealer
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
  /dealer/{itemIdentifier}/:
    delete:
      operationId: dealer_delete
      parameters:
      - description: A unique value identifying this dealer.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "204":
          content: {}
          description: ""
      tags:
      - dealer
      x-accepts: application/json
    get:
      operationId: dealer_read
      parameters:
      - description: A unique value identifying this dealer.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
          description: ""
      tags:
      - dealer
      x-accepts: application/json
    patch:
      operationId: dealer_partial_update
      parameters:
      - description: A unique value identifying this dealer.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dealer'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
          description: ""
      tags:
      - dealer
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
    put:
      operationId: dealer_update
      parameters:
      - description: A unique value identifying this dealer.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dealer'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
          description: ""
      tags:
      - dealer
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
  /gender/:
    get:
      operationId: gender_list
      parameters:
      - in: query
        name: with_uuid
        schema:
          type: string
      - in: query
        name: with_code
        schema:
          type: string
      - in: query
        name: with_name
        schema:
          type: string
      - in: query
        name: with_effectiveDate
        schema:
          type: string
      - in: query
        name: with_expirationDate
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Gender'
                type: array
          description: ""
      tags:
      - gender
      x-accepts: application/json
    post:
      operationId: gender_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gender'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gender'
          description: ""
      tags:
      - gender
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
  /gender/{itemIdentifier}/:
    delete:
      operationId: gender_delete
      parameters:
      - description: A unique value identifying this gender.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "204":
          content: {}
          description: ""
      tags:
      - gender
      x-accepts: application/json
    get:
      operationId: gender_read
      parameters:
      - description: A unique value identifying this gender.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gender'
          description: ""
      tags:
      - gender
      x-accepts: application/json
    patch:
      operationId: gender_partial_update
      parameters:
      - description: A unique value identifying this gender.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gender'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gender'
          description: ""
      tags:
      - gender
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
    put:
      operationId: gender_update
      parameters:
      - description: A unique value identifying this gender.
        in: path
        name: itemIdentifier
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gender'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gender'
          description: ""
      tags:
      - gender
      x-codegen-request-body-name: data
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    Branch:
      example:
        code: code
        createTime: 2000-01-23T04:56:07.000+00:00
        BranchType: local
        name: name
        updateTime: 2000-01-23T04:56:07.000+00:00
        itemIdentifier: itemIdentifier
        locked: true
        effectiveDate: 2000-01-23
        expirationDate: 2000-01-23
      properties:
        code:
          maxLength: 50
          minLength: 1
          title: Code
          type: string
        name:
          maxLength: 255
          title: Name
          type: string
        locked:
          nullable: true
          title: Locked
          type: boolean
        createTime:
          format: date-time
          nullable: true
          title: CreateTime
          type: string
        updateTime:
          format: date-time
          nullable: true
          title: UpdateTime
          type: string
        itemIdentifier:
          maxLength: 255
          minLength: 1
          title: ItemIdentifier
          type: string
        effectiveDate:
          format: date
          title: EffectiveDate
          type: string
        expirationDate:
          format: date
          nullable: true
          title: ExpirationDate
          type: string
        BranchType:
          enum:
          - local
          - main
          title: BranchType
          type: string
      required:
      - code
      - effectiveDate
      - itemIdentifier
      type: object
    DealerLocation:
      example:
        locationName: locationName
        city: city
        dealer: dealer
        addressLine1: addressLine1
        addressLine2: addressLine2
        postCode: postCode
        purge: true
        itemIdentifier: itemIdentifier
      properties:
        locationName:
          maxLength: 255
          title: LocationName
          type: string
        addressLine1:
          maxLength: 255
          title: AddressLine1
          type: string
        addressLine2:
          maxLength: 255
          title: AddressLine2
          type: string
        city:
          maxLength: 255
          title: City
          type: string
        postCode:
          maxLength: 255
          title: PostCode
          type: string
        purge:
          nullable: true
          title: Purge
          type: boolean
        itemIdentifier:
          maxLength: 255
          minLength: 1
          title: ItemIdentifier
          type: string
        dealer:
          nullable: true
          title: Dealer
          type: string
      required:
      - itemIdentifier
      type: object
    Dealer:
      example:
        code: code
        createTime: 2000-01-23T04:56:07.000+00:00
        name: name
        updateTime: 2000-01-23T04:56:07.000+00:00
        locations:
        - locationName: locationName
          city: city
          dealer: dealer
          addressLine1: addressLine1
          addressLine2: addressLine2
          postCode: postCode
          purge: true
          itemIdentifier: itemIdentifier
        - locationName: locationName
          city: city
          dealer: dealer
          addressLine1: addressLine1
          addressLine2: addressLine2
          postCode: postCode
          purge: true
          itemIdentifier: itemIdentifier
        itemIdentifier: itemIdentifier
        locked: true
        effectiveDate: 2000-01-23
        expirationDate: 2000-01-23
      properties:
        code:
          maxLength: 50
          minLength: 1
          title: Code
          type: string
        name:
          maxLength: 255
          title: Name
          type: string
        locked:
          nullable: true
          title: Locked
          type: boolean
        createTime:
          format: date-time
          nullable: true
          title: CreateTime
          type: string
        updateTime:
          format: date-time
          nullable: true
          title: UpdateTime
          type: string
        itemIdentifier:
          maxLength: 255
          minLength: 1
          title: ItemIdentifier
          type: string
        effectiveDate:
          format: date
          title: EffectiveDate
          type: string
        expirationDate:
          format: date
          nullable: true
          title: ExpirationDate
          type: string
        locations:
          items:
            $ref: '#/components/schemas/DealerLocation'
          type: array
      required:
      - code
      - effectiveDate
      - itemIdentifier
      - locations
      type: object
    Gender:
      example:
        code: code
        createTime: 2000-01-23T04:56:07.000+00:00
        name: name
        updateTime: 2000-01-23T04:56:07.000+00:00
        itemIdentifier: itemIdentifier
        locked: true
        effectiveDate: 2000-01-23
        expirationDate: 2000-01-23
      properties:
        code:
          maxLength: 50
          minLength: 1
          title: Code
          type: string
        name:
          maxLength: 255
          title: Name
          type: string
        locked:
          nullable: true
          title: Locked
          type: boolean
        createTime:
          format: date-time
          nullable: true
          title: CreateTime
          type: string
        updateTime:
          format: date-time
          nullable: true
          title: UpdateTime
          type: string
        itemIdentifier:
          maxLength: 255
          minLength: 1
          title: ItemIdentifier
          type: string
        effectiveDate:
          format: date
          title: EffectiveDate
          type: string
        expirationDate:
          format: date
          nullable: true
          title: ExpirationDate
          type: string
      required:
      - code
      - effectiveDate
      - itemIdentifier
      type: object
  securitySchemes:
    Basic:
      scheme: basic
      type: http

